version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecrf-app
    container_name: ecrf-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    networks:
      - ecrf

  web:
    image: nginx:alpine
    container_name: ecrf-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - ecrf

networks:
  ecrf:
    driver: bridge